# Generated by Django 4.1.7 on 2024-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('sim_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
